//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudTemple.MongoDB {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ConnectionString : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionString defaultInstance = ((ConnectionString)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionString())));
        
        public static ConnectionString Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://127.0.0.1:27017")]
        public string MongoDbLocalServer {
            get {
                return ((string)(this["MongoDbLocalServer"]));
            }
            set {
                this["MongoDbLocalServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cloudtemple")]
        public string MongoDbDefaultDatabase {
            get {
                return ((string)(this["MongoDbDefaultDatabase"]));
            }
            set {
                this["MongoDbDefaultDatabase"] = value;
            }
        }
    }
}
