
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudTemple.MySQL.Models
{
    using System.Linq;

    using Telerik.OpenAccess;
    using Telerik.OpenAccess.Metadata;

    public partial class MySqlDbContext : OpenAccessContext, IMySqlDbContextUnitOfWork
    {
        private static readonly string connectionStringName = @"MySqlConnection";

        private static readonly BackendConfiguration backend = GetBackendConfiguration();

        private static readonly MetadataSource metadataSource =
            XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");

        public MySqlDbContext()
            : base(connectionStringName, backend, metadataSource)
        {
        }

        public MySqlDbContext(string connection)
            : base(connection, backend, metadataSource)
        {
        }

        public MySqlDbContext(BackendConfiguration backendConfiguration)
            : base(connectionStringName, backendConfiguration, metadataSource)
        {
        }

        public MySqlDbContext(string connection, MetadataSource metadataSource)
            : base(connection, backend, metadataSource)
        {
        }

        public MySqlDbContext(
            string connection,
            BackendConfiguration backendConfiguration,
            MetadataSource metadataSource)
            : base(connection, backendConfiguration, metadataSource)
        {
        }

        public IQueryable<Salereport> Salereports => this.GetAll<Salereport>();

        public static BackendConfiguration GetBackendConfiguration()
        {
            var backend = new BackendConfiguration { Backend = "MySql", ProviderName = "MySql.Data.MySqlClient" };

            CustomizeBackendConfiguration(ref backend);

            return backend;
        }

        /// <summary>
        ///     Allows you to customize the BackendConfiguration of MySqlDbContext.
        /// </summary>
        /// <param name="config">The BackendConfiguration of MySqlDbContext.</param>
        static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
    }
}

#pragma warning restore 1591